name: Update Binary Choices

on:
    push:
        paths:
            - "binaries.yml"
    pull_request:
        paths:
            - "binaries.yml"
    workflow_dispatch:

jobs:
    update-choices:
        runs-on: ubuntu-latest
        permissions:
            actions: write
        steps:
            - uses: actions/checkout@v4

            - name: Update BINARY_TYPES variable
              run: |
                  BRANCH=${GITHUB_REF#refs/heads/}
                  TYPES=$(yq -o=json '.binaries | keys' binaries.yml)
                  gh variable set BINARY_TYPES_${BRANCH} --body "$TYPES"
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
