name: Update Workflow Options

on:
    push:
        paths:
            - "binaries.yml"
            - ".github/workflows/update-workflow-options.yml"
    workflow_dispatch:

jobs:
    update-workflow:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                token: ${{ secrets.WORKFLOW_TOKEN }}

            - name: Install dependencies
              run: pip install pyyaml ruamel.yaml

            - name: Update workflow options
              run: |
                python3 .github/workflows/scripts/update_workflow_options.py \
                  --workflow .github/workflows/mirror-binaries.yml \
                  --config binaries.yml

            - name: Commit and push if changed
              run: |
                if git diff --quiet; then
                  echo "No changes detected in workflow file"
                  exit 0
                fi

                git config user.name "GitHub Actions Bot"
                git config user.email "actions@github.com"
                git add .github/workflows/mirror-binaries.yml
                git commit -m "Update binary type options [skip ci]"
                git push
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
