name: Update Binary Choices

on:
  push:
    paths:
      - 'binaries.yml'
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-choices:
    runs-on: ubuntu-latest
    permissions:
      actions: write  # Needed to update Variables
    steps:
      - uses: actions/checkout@v4
      
      - name: Update BINARY_TYPES variable
        run: |
          TYPES=$(yq -o=json '.binaries | keys' binaries.yml)
          gh variable set BINARY_TYPES "$TYPES" --body "Available binary types"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
