name: Update Binary Choices

on:
  push:
    paths:
      - 'binaries.yml'
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-choices:
    runs-on: ubuntu-latest
    permissions:
      actions: write  # Needed to update Variables
    steps:
      - uses: actions/checkout@v4
      
      - name: Update binary choices
        uses: actions/github-script@v7
        with:
          script: |
            const yaml = require('js-yaml');
            const fs = require('fs');
            
            const config = yaml.load(fs.readFileSync('binaries.yml', 'utf8'));
            const binaryTypes = Object.keys(config.binaries);
            
            await github.rest.actions.updateRepoVariable({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'BINARY_TYPES',
              value: JSON.stringify(binaryTypes)
            }); 